config/routes.rb
Rails.application.routes.draw do
  get 'mentor_subcats/new'

  # root 'sessions#new'
  root 'categories#index'
  get 'sessions/new'

  # get '/signup', to: 'users#new'
  # post '/signup', to: 'users#create'
  # get '/profile', to: 'users#show'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get '/newmentor', to: 'mentor_infos#new'
  # put '/newmentor', to: 'mentor_infos#create'
  # get '/mentorprofile', to: 'mentor_infos#show'
resources :mentor_infos

  #
  # get '/addmentor', to: 'mentor_infos#new'
  # post '/addmentor', to: 'mentor_infos#create'
  # get '/mentor_infos/edit', to: 'mentor_infos#edit'

  get '/booking/:mentor_id', to: 'bookings#new'
  post '/booking', to: 'bookings#create'


  get '/mentor_availabilities', to: 'mentor_availabilities#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  resources :subcategories
  get '/bookings/notification', to: 'bookings#notification'
  resources :bookings


  get 'bookings/:id/confirm', to: 'bookings#change_status'
  get 'search/new', to: 'search#new'
  get 'search/create', to: 'search#create'

end

app/models/mentor_info.rb
class MentorInfo < ApplicationRecord
  belongs_to :user
  has_many :subcategories
  has_many :bookings


end

app/controllers/mentor_infos_controller.rb
class MentorInfosController < ApplicationController
  before_action :ensure_logged_in
  before_action :is_mentor, only: [:create,:update,:edit]
  def index
    @mentor_infos = MentorInfo.all
  end

  def show
    @user = current_user
    @mentor = User.find(params[:id])

    if @user.is_mentor && @mentor.id != @user.id
      flash[:notice] = "Can't view another mentors profile page!"
      redirect_to mentor_info_path(current_user.id)
    end

    @mentor_info = @mentor.mentor_info
    @bookings = Booking.all
    @booking = Booking.new

  end

  def new
    @mentor_info = MentorInfo.new
    @categories = Category.all
    @subcategories = Subcategory.all

  end

  def create
    current_user.create_mentor_info(summary: params[:mentor_info][:summary])
    subcat_add = Subcategory.where(id: params["mentor_info"]["subcategories_ids"])
    subcat_add.each do |subcat|
      current_user.subcategories << subcat
    end
    redirect_to mentor_info_path(current_user.id)
  end

  def edit
    @user = current_user
    # @mentor_info = @user.mentor_info ? @user.mentor_info : @user.create_mentor_info
    @mentor_info = current_user.mentor_info

    @categories = Category.all
    @subcategory = Subcategory.all
  end

  def update
    @user = current_user

    @user.mentor_info.summary = params[:mentor_info][:summary]
    @user.mentor_info.save
    subcat_add = Subcategory.where(id: params[:mentor_info][:subcategories_ids])
    @user.subcategories.delete_all
    subcat_add.each do |subcat|
      @user.subcategories << subcat
    end
      redirect_to mentor_info_path(@user.id)
  end



end

app/helpers/mentor_infos_helper.rb
module MentorInfosHelper
end

app/views/mentor_infos/_mentor_bookings.html.erb
<div class="container-confirmed">
  <h2>Confirmed bookings</h2>
  <%if bookings.pluck(:status).count(true) == 0%>
  <%='There are no confirmed bookings.'%>
  <%else%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Date</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      <% bookings.each do |apt| %>
        <%if apt.status == true %>
      <tr>
        <td><%=apt.student.first_name%></td>
        <td><%=apt.student.last_name%></td>
        <td><%=apt.student.email%></td>
        <td><%=apt.booking_date.strftime("%m/%d/%Y")%></td>
        <td><%=apt.booking_time.strftime("%I:%M%p")%></td>
      </tr>
    </tbody>
    <%end%>
    <%end%>
  </table>
  <%end%>
</div><br>




<div class="container-unconfirmed">
  <h2>Pending bookings</h2>
  <%if bookings.pluck(:status).count(false) == 0%>
  <%='There are no pending bookings.'%>
  <%else%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Date</th>
        <th>Time</th>
        <th>Confirm</th>
      </tr>
    </thead>
    <tbody>
      <% bookings.each do |apt| %>
        <%if apt.status == false %>
      <tr>
        <td><%=apt.student.first_name%></td>
        <td><%=apt.student.last_name%></td>
        <td><%=apt.booking_date.strftime("%m/%d/%Y")%></td>
        <td><%=apt.booking_time.strftime("%I:%M%p")%></td>
        <td><button class="button" onclick="window.location.reload()" id="<%= apt.id%>">CONFIRM</button></td>
      </tr>
    </tbody>
    <%end%>
    <%end%>
  </table>
  <%end%>
</div>

app/views/mentor_infos/_mentor_info_edit.html.erb
<div>
  <%= form_for(@mentor_info) do |f| %>
    <%= f.label :summary%><br>
    <%= f.text_area :summary%><br>
    <%= f.collection_check_boxes :subcategories_ids, Subcategory.all, :id, :name, checked: current_user.subcategory_ids %><br>
    <%= f.submit "Submit Mentor Info" %>
  <% end %><br>
</div>

app/views/mentor_infos/edit.html.erb
<%= render 'mentor_info_edit' %>

app/views/mentor_infos/new.html.erb
<%= render 'mentor_info_edit'%>

app/views/mentor_infos/show.html.erb
<div class="alert alert-success">
  <strong class="welcome">Welcome <%= current_user.first_name%>!</strong>
</div>

<div class="container-fluid">
  <div class="mentor-info-container">
    <%= image_tag(@mentor.avatar.url(:medium), class:"mentor-picture")%>

    <div class="av-button">
      <%if @user.is_mentor %>

      <label class="switch", id="your_id">
            <input type="checkbox"  <%= current_user.mentor_info.availability ? "checked": ""%>>
            <span class="slider round", id="circle"></span>
        </label>
      <% else %>
        <%= render 'bookings/new' %>
      <%end%>
    </div>

    <% if @mentor.mentor_info %>
    <h3>Summary:</h3> <%= @mentor.mentor_info.summary %><br>
    <ul class="mentorcats">
      <h2>Things I Teach:</h2>
      <% @mentor.subcategories.each do |subcat| %>
        <li><%= subcat.name %></li>
      <% end %>
    </ul>
    <% end %> <br>

  </div>

  <div class="student-details">

    <% if current_user.is_mentor  %>
      <%= render "mentor_bookings", bookings: current_user.mentor_bookings %>
    <%end%>



  </div>
</div>