config/routes.rb
Rails.application.routes.draw do
  get 'mentor_subcats/new'

  # root 'sessions#new'
  root 'categories#index'
  get 'sessions/new'

  # get '/signup', to: 'users#new'
  # post '/signup', to: 'users#create'
  # get '/profile', to: 'users#show'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get '/newmentor', to: 'mentor_infos#new'
  # put '/newmentor', to: 'mentor_infos#create'
  # get '/mentorprofile', to: 'mentor_infos#show'
resources :mentor_infos

  #
  # get '/addmentor', to: 'mentor_infos#new'
  # post '/addmentor', to: 'mentor_infos#create'
  # get '/mentor_infos/edit', to: 'mentor_infos#edit'

  get '/booking/:mentor_id', to: 'bookings#new'
  post '/booking', to: 'bookings#create'


  get '/mentor_availabilities', to: 'mentor_availabilities#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  resources :subcategories
  get '/bookings/notification', to: 'bookings#notification'
  resources :bookings


  get 'bookings/:id/confirm', to: 'bookings#change_status'
  get 'search/new', to: 'search#new'
  get 'search/create', to: 'search#create'

end

app/models/category.rb
class Category < ApplicationRecord
has_many :subcategories
has_many :users, through: :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @user = current_user

  end

  def show
    @category = Category.find(params[:id])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% if logged_in? == false  %>
<div class="modal show" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          
          <h4 class="modal-title">Welcome to Kaizen</h4>
        </div>
        <div class="modal-body">
          <p>Find a mentor in your neighbourhood to teach you a new skill</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
<% end %>













<link href="https://fonts.googleapis.com/css?family=Baloo+Chettan" rel="stylesheet">
<link href=“https://fonts.googleapis.com/css?family=Comfortaa|Nosifer” rel=“stylesheet”>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">



    <div class="mentor_info">


      <div class="row cards">
        <div class="col-md-12 title">
          <h3>What do you want to learn?</h3>
        </div>
        <% @categories.each do |cat| %>

          <div class="card col-md-3">
         <p class="card-text">
           <div class="card-body">
            <% if logged_in? %>
              <h4 class="card-title"><%= link_to cat.name, category_path(cat.id)  %></h4>
            <% else %>
              <h4 class="card-title"><%= link_to cat.name, login_path  %></h4>
            <% end %>
           </div>
         </p>
       </div>
       <%end%>

       </div>
     </div>



    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100 max-size-image" src="https://static.pexels.com/photos/34627/pexels-photo.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 max-size-image" src="https://static.pexels.com/photos/102127/pexels-photo-102127.jpeg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 max-size-image" src="https://static.pexels.com/photos/357743/pexels-photo-357743.jpeg" alt="Third slide">
      </div>
    </div>

  </div>

app/views/categories/show.html.erb
<script>
function initMap() {
  var current_user_codinates = <%= Geocoder.coordinates(current_user.postal_code)%>
  var myLatLng = { lat:  current_user_codinates[0], lng:  current_user_codinates[1]};

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: myLatLng
  });

  var logs = <%= postal_code_to_long_lat(@category)%>

  for(var i=0;i < logs.length;i++){
    //console.log(logs[i][0]);

  var marker = new google.maps.Marker({
    position: {lat: logs[i][0], lng: logs[i][1]},
    map: map,
    title: "yolo"
  });
}
}

</script>

<h1><%= @category.name %></h1>

<div id="map" style="height: 300px; width: 100%;"></div>

<div class="mentor_info">
  <div class="row">
    <% @category.subcategories.each do |subc| %>
      <div class="card col-md-4">
     <p class="card-text">
       <div class="card-body">
         <h4 class="card-title"><%= link_to subc.name, subcategory_path(subc) %></h4>
       </div>
     </p>
   </div>
<%end%>
   </div>
 </div>

 

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCaqdxtLVgAPgOwN_gZhMfeascKFwin1M&callback=initMap">
</script>