config/routes.rb
Rails.application.routes.draw do
  get 'mentor_subcats/new'

  # root 'sessions#new'
  root 'categories#index'
  get 'sessions/new'

  # get '/signup', to: 'users#new'
  # post '/signup', to: 'users#create'
  # get '/profile', to: 'users#show'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get '/newmentor', to: 'mentor_infos#new'
  # put '/newmentor', to: 'mentor_infos#create'
  # get '/mentorprofile', to: 'mentor_infos#show'
resources :mentor_infos

  #
  # get '/addmentor', to: 'mentor_infos#new'
  # post '/addmentor', to: 'mentor_infos#create'
  # get '/mentor_infos/edit', to: 'mentor_infos#edit'

  get '/booking/:mentor_id', to: 'bookings#new'
  post '/booking', to: 'bookings#create'


  get '/mentor_availabilities', to: 'mentor_availabilities#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  resources :subcategories
  get '/bookings/notification', to: 'bookings#notification'
  resources :bookings


  get 'bookings/:id/confirm', to: 'bookings#change_status'
  get 'search/new', to: 'search#new'
  get 'search/create', to: 'search#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :student, class_name: "User"
  belongs_to :mentor, class_name: "User"
  validate :booking_date_future



  scope :confirmed, -> { where(status: true) }
  scope :unconfirmed, -> { where(status: false) }


  def booking_date_future
    if booking_date < Date.today
      errors.add(:booking_date, message:"Booking date should be in the future.") 
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
has_many :subcategories
has_many :users, through: :subcategories
end

app/models/mentor_info.rb
class MentorInfo < ApplicationRecord
  belongs_to :user
  has_many :subcategories
  has_many :bookings


end

app/models/mentor_subcat.rb
class MentorSubcat < ApplicationRecord
  belongs_to :user

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_one :mentor_info
  has_and_belongs_to_many :subcategories

  has_many :mentor_bookings, :foreign_key => 'mentor_id', :class_name => 'Booking'
  has_many :student_bookings, :foreign_key => 'student_id', :class_name => 'Booking'
  has_secure_password



  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: "image/jpeg"
  validates :first_name, :last_name, :email, presence: true

  def self.mentors
    where("is_mentor = true")
  end

  def self.students
    where("is_mentor = false")
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @mentor_info = MentorInfo.find(params[:mentor_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.mentor_id = params[:booking][:mentor_id]
    @booking.student_id = current_user.id
    @booking.booking_date = params[:booking][:booking_date]
    @booking.booking_time = params[:booking][:booking_time]
    @booking.status = false

    if @booking.save
      flash[:notice] = "Booking successfully created"
      redirect_to root_url
    else
      flash[:notice] = "Unable to create booking, please check date"
      redirect_to mentor_info_path(params[:booking][:mentor_id])
    end
  end

 def index
    @bookings = Booking.all
  end

  def show
    @booking = current_booking
  end

 def destroy

 end


 def change_status
   booking_find = Booking.find(params[:id])
   booking_find.status = true
   booking_find.save
   render json: booking_find.status
 end

 def notification
   return "not logged_in" unless current_user
   if current_user.is_mentor
     notifications = current_user.mentor_bookings.unconfirmed
     url = "/mentor_infos/#{current_user.id}"
  else
     notifications = current_user.student_bookings.where(status: false)
    url = "/users/#{current_user.id}"
  end
  arr = []
  notifications.each do |n|
    hash = {}
    hash[:name] = n.student.first_name
    hash[:date] = n.booking_date.strftime("%m/%d/%Y")
    hash[:time] = n.booking_time.strftime("%I:%M%p")
    hash[:url] =  url
    hash[:status] = n.status ? "Confirmed" : "Unconfirmed"
    arr << hash
  end
   render json: {number: notifications.count, notification: arr}
 end

private
  def booking_params
    params.require(:booking).permit(:booking_date, :booking_time, :mentor_id, :student_id)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
    @results = Subcategory.where("name ILike ?",  "%#{params[:search]}%")
    render 'results'
  end

  def new

  end

  private

  def params_search
    params.require(:search).permit(:Subcategory, :name)

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      if user.is_mentor
        if user.mentor_info
          redirect_to mentor_info_path(current_user.id)
        else
          redirect_to new_mentor_info_path
        end
      else

        redirect_to user_path(current_user.id)
      end

    else
      render 'new'
    end
  end

  def destroy
    log_out?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :name, :email

  def show
    @user = current_user

    
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      if @user.is_mentor
        redirect_to new_mentor_info_path
      else
        redirect_to user_path(current_user.id)
      end
    else
      render 'new'
    end




  end



private
  def user_params
    params.require(:user).permit(:postal_code, :first_name, :last_name, :email, :is_mentor, :phone, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mentor_infos_helper.rb
module MentorInfosHelper
end

app/helpers/mentor_subcats_helper.rb
module MentorSubcatsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # require 'geocoder'
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out?
      session[:user_id] = nil
  end

  def near_me(sub_cat)
    everyone_else = sub_cat.users.where(is_mentor: true)
    everyone_else.select do |mentor|
      dist = Geocoder::Calculations.distance_between(current_user.postal_code, mentor.postal_code )

      dist <= 4.0
    end
  end

  def postal_code_to_long_lat(cat)
    users = cat.users.where(is_mentor: true)
    nearme = users.select do |mentor|
        dist = Geocoder::Calculations.distance_between(current_user.postal_code, mentor.postal_code )

        dist <= 4.0
    end
    cordinates = []
    nearme.each do |mentor|
      cordinates << Geocoder.coordinates(mentor.postal_code)
    end
    p cordinates
  end

end

app/helpers/subcataegories_helper.rb
module SubcataegoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<footer>

  <div class="card" style="height:50%" >
    <div class="card-header">

    </div>
    <div class="card-body">
         <!--/Copyright-->
      <h6 class="card-title">© 2017 Copyright: Kaizen</h6>
      <p class="card-text">About | Contact | Help | Code of Ethics & Standards</p>

    </div>
  </div>


</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <%= link_to "Kaizen", categories_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

<% if logged_in? %>

  <% if current_user.is_mentor == false%>

    <li class="nav-item">
    <%= link_to "Book A Mentor", categories_path, class: "nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Profile", current_user, class: "nav-link"%>
    </li>
  <%end%>

  <% if current_user.is_mentor %>

    <li class="nav-item">
      <%= link_to "Profile", "/mentor_infos/#{current_user.id}", class: "nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Edit",  edit_mentor_info_path(current_user.id), class: "nav-link" %>
    </li>



  <% end %>
  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Notification <span class="number-notifications">  </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

          </div>
        </li>

<li class="nav-item">
  <%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %>

</li>
<%=form_tag('/search/create', method: 'get', class: "form-inline my-2 my-lg-0") do %>
  <%= text_field_tag 'search' %>
  <%= submit_tag 'search', class: "btn btn-outline-success my-2 my-sm-0"%>
<%end %>
<% else%>
  <li class="nav-item">
    <%= link_to "Log In", login_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
  </li>

<% end%>
    </ul>



  </div>

</nav>

  </div>
  <% if flash[:notice] %>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">


          <div class="alert alert-info" role="alert"><%= flash[:notice] %>
            <button type="button" class="close" data-toggle="modal" data-target="#exampleModal">
              <span aria-hidden="true">&times;</span>
    </button></div>

    </div>
  </div>
  <script>
    $('#exampleModal').modal('toggle')
  </script>
  <% end %>




</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaizenAlpha</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

        <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>

  </head>

  <body background="https://assets.awwwards.com/awards/images/2015/04/pattern.jpg">
    <%= render 'layouts/header' %>

    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>